### ISSUE TITLE
[Issue] Matches not showing

### ISSUE THREAD

**Issue by SaturnusDJ** [tinderjs/tinder-desktop#2]
Same as https://github.com/mfkp/tinderplusplus/issues/41 indeed.

Matches disappear without clear reason. Maybe the cookie drop causes this. Login again via Facebook, but matches still gone. Clearing cache and signing in again doesn't help either.

Sometimes this works: Sign in and wait for some minutes, not even closing the swipe-out-of-people-error. It feels like pure luck. Trial and error until all of a sudden the matches are back for a while.

**Comment by mayeaux** [comment]
I had this same issue before but it cleared up randomly and hasn't happened since. What's basically happening is that the app is using your credentials to use tinderjs and hit Tinders API and taking that response to build out the frontend. I've been tinkering with the tinderjs module and there's times where it can just sputter out and not return anything, I think something can be implemented to fix this where we retry the request over and over until it returns something, or at least tell the user that Tinder isn't responding rather than just have it hang forever. Will look into this.

**Comment by SaturnusDJ** [comment]
Sweet.

Little offtopic: Is Tinder able to see we are using an unofficial app? Probably not by the commands, but maybe behavior. Like this match list issue. What annoyed me is how the home page always immediately starts the swipe sequence. That's why I changed the layout in my unstable. The always present static bar basically became the 'home page.'

**Comment by mayeaux** [comment]
No, unless Tinder has implemented an algorithm to detect programmatic use they won't be detecting us, to them we're just hitting them from an Android device (and I don't think they have implemented something like that tbh).

And I think what the original designer of this app was going for was cloning the Tinder client on a desktop setting, which is why the screen is the shape of a cellphone etc. Not necessarily the best design decision though and we can adjust it to what we want, personally I would prefer to land on messages on a login screen but that's just me.

**Comment by mayeaux** [comment]
Something to do with the token expiring (or being invalidated by Tinder).

Solution right now is to logout/close app, reopen app, login.

**Comment by stuwil** [comment]
Only partially resolved by #65 with proper session invalidation.
