### ISSUE TITLE
Discussion [Future of Tinder-desktop GUI]

### ISSUE THREAD

**Issue by mayeaux** [tinderjs/tinder-desktop#4]
Hey @SaturnusDJ ,

Let's use this issue to discuss the design decisions broadly of tinder-desktop.

I've checked out your pull requests and haven't pulled it. For one, there are a couple issues, like the zip file being committed to source, if I was to merge this PR I would ask you to do things like remove that zip file first.

The other is I'm not totally sure exactly what has changed and I've noticed a 'bug' or two as well. 
![screen shot 2016-03-15 at 9 45 24 am](https://cloud.githubusercontent.com/assets/7200471/13783969/177f6602-ea93-11e5-9153-530d50dd29db.png)

For example, you can see the text profile isn't being displayed properly (it's not centered). There's also little issues like inline CSS being used (harder to maintain).

https://github.com/tinderjs/tinder-desktop/pull/1/files#diff-c5ccb23a8eb2fc0c7e51b595a2eae347R112

For me to accept all the frontend changes, I would first like to know what each of them does. There's a few ways we could do this:
1) You could post screenshots like you did with that one screenshot, which was immensely helpful for me
2) We could go over it with a screensharing program and you could explain them to me
3) We could go through it line by line through the PR and see what is going on

The other thing is that in regards to the GUI, I think we should only change things if we see a definite benefit to the change. For example, changing the settings to a gear button, it's mostly a matter of opinion on if that is a change we would like (personally, I like it) but unless we've identified something as an issue that needs to be fixed, we should probably open a discussion on the GUI features that we're noticing as subpar and that we would like to fix before we go in and change them.

Everything make sense? Also, in more broad frontend strategic views, I'm wondering if we should make this app a fullscreen application. For example, one of  the things that I don't like is that on the messages page the photo for the matches are so small it's very hard to see what they look like. For me, that's a design error that we should address, perhaps by making it fullscreen. 

![screen shot 2016-03-15 at 9 55 50 am](https://cloud.githubusercontent.com/assets/7200471/13784259/2aaa11ea-ea94-11e5-8abb-95454ef7484b.png)
![screen shot 2016-03-15 at 9 55 29 am](https://cloud.githubusercontent.com/assets/7200471/13784260/2b08eb8e-ea94-11e5-8570-8551a771cf84.png)

Here's the comparable sizes on WhatsApp and Facebook Messenger, and it could be argued having a larger size on Tinder is even more important because of how you don't know the people very well and how important appearance is. Let me know what you think. :)

**Comment by SaturnusDJ** [comment]
Hi @mrmayfield 

Yes I can remove the unnecessary files when the moment is there. Don't know how to exclude them from pull, that would be easier.

The profile text was centered, I changed it to be aligned left so it would look more like tinder-mobile. Your screenshot clearly shows the disadvantage. I can change it back to be centered. A better solution, in my opinion, would be to still align left but center the whole text area and limit it's width to approximately the size of picture above to keep it readable.

The inline was done on purpose because I don't like the solution. It's about undo-swipe. The position of this object should be relative to the picture stack but I don't know how to code it yet. I can put it in .css with comment.

Concerning the changes. Do you want to know every single line or more the general ideas?

I like to optimize/improve GUI, but of course that's my opinion. Continuously improving is something I really like and keeps me going, but I understand some boundaries are needed.

Fullscreen as option is okay with me, forcing fullscreen I don't like. I always use Tinder next to browsing, etc, etc.

Maybe we can make profile pictures in messages screen hoverable. You don't like to open the profiles? That's what I do when really wanting to look up pictures.
What I already did was using the native size for the big pictures, so they became sharper (300 -> 320px).

**Comment by SaturnusDJ** [comment]
Bio adjusted as described above. (Details in commit.)
Inline moved to file.

I just checked what image sizes are natively available from Tinder: 84px, 172px, 320px, 640px. We should make a gallery/lightbox for the 640px.
